# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true
    architecture: 'x64'
- task: Bash@3
  inputs:
    # install requirements specified in bash script
    filePath: 'environment_setup/install-requirements.sh'  
- task: AzureCLI@2
  displayName: Install Azure CLI'
  inputs:
    azureSubscription: 'mlOpsDemo'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@2
  displayName: 'Create/Use ML Workspace'
  inputs:
    azureSubscription: 'mlOpsDemo'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az ml workspace create -g $(ml.resourceGroup) -w $(ml.workspace) -l $(ml.region) --exist-ok --yes'

- task: AzureCLI@2
  displayName: 'Create/Use Compute Instance'
  inputs:
    azureSubscription: 'mlOpsDemo'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az ml computetarget create amlcompute -g $(ml.resourceGroup) -w $(ml.workspace) -n $(ml.computeName) -s $(ml.computeVMSize) --min-nodes $(ml.computeMinNodes) --max-nodes $(ml.computeMaxNodes) --idle-seconds-before-scaledown $(ml.computeIdleSecs)'

